openapi: 3.0.1
info:
  title: VASP ID API
  version: '1.0'
  description: Enclave API getOwnVASPID
paths:
  /v1/vasps/self:
    get:
      description: >
        VASP (Virtual Asset Service Provider) can check its own VASP ID using
        this API.
      tags:
        - Enclave API
      operationId: getVaspId
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  vaspId:
                    type: string
                    description: Unique identifier of the VASP.
                    example: '15952089931162058999'
              examples:
                successexample:
                  value:
                    vaspId: '15952089931162058999'
        '400':
          description: 400 Bad Request Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      Error message.   - Invalid input parameters   - Missing
                      Required Parameters   - Inactive VASP
                    example: MISSING-VERIFICATION-UUID
              examples:
                400Errorexample:
                  value:
                    code: MISSING-REQUIRED-BENEFICIARY-INFO
                    message: '`requiredBeneficiaryInfo` is required.'
        '404':
          description: 404 Resource Not Found Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      Error message.   It could be returned in the following
                      cases:   - When request with a non-existent resource is
                      provided.
                    example: VERIFICATION-NOT-FOUND
                  message:
                    type: string
                    description: |
                      Explanation about the error that is returned in CODE.
                    example: >-
                      Verification(9faab87c-54a6-4145-baa9-7a3a42d7410c) is not
                      found
              examples:
                404Errorexample:
                  value:
                    code: VERIFICATION-NOT-FOUND
                    message: >-
                      Verification(9faab87c-54a6-4145-baa9-7a3a42d7410c) is not
                      found
        '408':
          description: 408 Request Timeout Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      Error message.   It could be returned in the following
                      cases:   When a timeout occurs during the processing of a
                      request.
                    example: REQUEST-TIMEOUT
                  message:
                    type: string
                    description: |
                      Explanation about the error that is returned in code.
                    example: timeout of 5000ms exceeded
              examples:
                408Errorexample:
                  value:
                    code: REQUEST-TIMEOUT
                    message: timeout of 5000ms exceeded
